### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by Marko298** [vkovic/laravel-custom-casts#18]
In native laravel cast, you can add params for casts. For example [date](https://laravel.com/docs/6.x/eloquent-mutators#date-casting). 
Adding this feature gives more control over casting process.

```php
class User extends Model {
  protected $casts = [
    'avatar' => 'file:disk',
  ];
}
```

**Comment by vkovic** [comment]
Funny, I was thinking the same thing since we (@jimhlad and me) added support for the named casts but in the lack of time I was unable to work on it.

@Marko298 Maybe you can check the code, as you already did some cool changes and try to implement this one - i'll support you.

Of course if you do not have time yourself, I'm planning to do this in the couple of weeks.

Cheers 🍻

**Comment by Marko298** [comment]
I wrote down this in order to have some plans. I will create pull requests to all features on the weekend

**Comment by vkovic** [comment]
Great!

**Comment by Marko298** [comment]
I like the idea of this package a lot and I think it will have a great future.
