### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by pr4xx** [vkovic/laravel-custom-casts#20]
```
The optional getAttribute method receives the raw $value from the database, and should return a mutated value. If this method is omitted, the raw database value will be returned.
```

Is it really `getAttribute` or rather `castAttribute`? The example is kinda vague about this.

**Comment by vkovic** [comment]
@pr4xx you're right, it's a typo. It should actually be `castAttribute`. Since I'm not an native english speaker, maybe you can try to replace `getAttribute` with `castAttribute` and formulate sentence to be more readable. 

On the other side, if you do not have time or don't want to bother with PR, i'll do it.

Thanks!
